config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_config.toml:
    src: config/atuin/config.toml
    dst: ~/.config/atuin/config.toml
    chmod: '600'
  f_config.conf:
    src: config/neofetch/config.conf
    dst: ~/.config/neofetch/config.conf
  f_settings.json:
    src: config/zed/settings.json
    dst: ~/.config/zed/settings.json
    chmod: '600'
  f_zeal.conf:
    src: config/Zeal/Zeal.conf
    dst: ~/.config/Zeal/Zeal.conf
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_pypoetry_config.toml:
    src: config/pypoetry/config.toml
    dst: ~/.config/pypoetry/config.toml
    chmod: '600'
  f_user-dirs.dirs:
    src: config/user-dirs.dirs
    dst: ~/.config/user-dirs.dirs
    chmod: '600'
  f_user-dirs.locale:
    src: config/user-dirs.locale
    dst: ~/.config/user-dirs.locale
  f_2026-01-21_03-07-05_linux.conf:
    src: boot/loader/entries/2026-01-21_03-07-05_linux.conf
    dst: /boot/loader/entries/2026-01-21_03-07-05_linux.conf
    chmod: '755'
  f_pacman.conf:
    src: etc/pacman.conf
    dst: /etc/pacman.conf
  f_host.conf:
    src: etc/host.conf
    dst: /etc/host.conf
  f_locale.conf:
    src: etc/locale.conf
    dst: /etc/locale.conf
  f_locale.gen:
    src: etc/locale.gen
    dst: /etc/locale.gen
  f_nanorc:
    src: etc/nanorc
    dst: /etc/nanorc
  f_netconfig:
    src: etc/netconfig
    dst: /etc/netconfig
  f_00-keyboard.conf:
    src: etc/X11/xorg.conf.d/00-keyboard.conf
    dst: /etc/X11/xorg.conf.d/00-keyboard.conf
  f_10-monitors.conf:
    src: etc/X11/xorg.conf.d/10-monitors.conf
    dst: /etc/X11/xorg.conf.d/10-monitors.conf
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_config.yml:
    src: config/gh/config.yml
    dst: ~/.config/gh/config.yml
    chmod: '600'
  f_hosts.yml:
    src: config/gh/hosts.yml
    dst: ~/.config/gh/hosts.yml
    chmod: '600'
  f_config:
    src: bundle/config
    dst: ~/.bundle/config
  f_blacklist.conf:
    src: etc/modprobe.d/blacklist.conf
    dst: /etc/modprobe.d/blacklist.conf
  f_htoprc:
    src: config/htop/htoprc
    dst: ~/.config/htop/htoprc
    chmod: '600'
  f_spaceship.zsh:
    src: config/spaceship.zsh
    dst: ~/.config/spaceship.zsh
  f_vimrc:
    src: etc/vimrc
    dst: /etc/vimrc
  f_foremost.conf:
    src: etc/foremost.conf
    dst: /etc/foremost.conf
    chmod: '444'
  f_hosts:
    src: etc/hosts
    dst: /etc/hosts
  f_makepkg.conf:
    src: etc/makepkg.conf
    dst: /etc/makepkg.conf
  f_torrc:
    src: etc/tor/torrc
    dst: /etc/tor/torrc
  f_vbox.cfg:
    src: etc/vbox/vbox.cfg
    dst: /etc/vbox/vbox.cfg
  f_config.json:
    src: config/arduino-ide/config.json
    dst: ~/.config/arduino-ide/config.json
    chmod: '666'
  f_preferences:
    src: config/arduino-ide/Preferences
    dst: ~/.config/arduino-ide/Preferences
    chmod: '600'
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_freshrss.json:
    src: config/news-flash/freshrss.json
    dst: ~/.config/news-flash/freshrss.json
  f_newsflash_gtk.json:
    src: config/news-flash/newsflash_gtk.json
    dst: ~/.config/news-flash/newsflash_gtk.json
  f_bookmarks:
    src: config/gtk-3.0/bookmarks
    dst: ~/.config/gtk-3.0/bookmarks
profiles:
  archlinux:
    dotfiles:
    - f_config.toml
    - f_config.conf
    - f_settings.json
    - f_zeal.conf
    - f_gitconfig
    - f_zshrc
    - f_pypoetry_config.toml
    - f_user-dirs.dirs
    - f_user-dirs.locale
    - f_2026-01-21_03-07-05_linux.conf
    - f_pacman.conf
    - f_host.conf
    - f_locale.conf
    - f_locale.gen
    - f_nanorc
    - f_netconfig
    - f_00-keyboard.conf
    - f_10-monitors.conf
    - f_aliases
    - f_config.yml
    - f_hosts.yml
    - f_config
    - f_blacklist.conf
    - f_htoprc
    - f_spaceship.zsh
    - f_vimrc
    - f_foremost.conf
    - f_hosts
    - f_makepkg.conf
    - f_torrc
    - f_vbox.cfg
    - f_config.json
    - f_preferences
    - f_bashrc
    - f_freshrss.json
    - f_newsflash_gtk.json
    - f_bookmarks
  homelab:
    dotfiles:
    - f_config.toml
    - f_config.conf
    - f_gitconfig
    - f_zshrc
    - f_htoprc
    - f_aliases
    - f_spaceship.zsh
