---
- name: Instalação das ferramentas python
  hosts: localhost

  tasks:
    - name: Install ignr
      community.general.pipx:
        name: ignr
    
    - name: Install pepotron
      community.general.pipx:
        name: pepotron
    
    - name: Install mkx
      community.general.pipx:
        name: mkx
    
    - name: Install smokeshow
      community.general.pipx:
        name: smokeshow  # Coverage badge (Samuel Colvin) -> https://github.com/samuelcolvin/smokeshow