- hosts: localhost
  tasks:
    - ansible.builtin.debug:
        msg: play1
- name: aur
  import_playbook: aur.yml
- name: dev
  import_playbook: dev.yml
- name: python
  import_playbook: python.yml
- name: gui
  import_playbook: gui.yml
- name: latex
  import_playbook: latex.yml
